---
- name: Update Debian based distros
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Update Consul
  include_tasks: consul.yml

- name: Does postgresql.conf exist?
  stat: 
    path: /etc/postgresql/14/main/postgresql.conf
  register: postgresql_conf

- name: Update postgresql.conf for listening IPs
  when: postgresql_conf.stat.exists
  notify: restart_postgres
  lineinfile:
    path: "/etc/postgresql/14/main/postgresql.conf"
    line: "listen_addresses = '*'"
    state: "{{postgres_state}}"

- name: Update postgresql.conf for listening IPs
  when: postgresql_conf.stat.exists
  notify: restart_postgres
  lineinfile:
    state: "{{postgres_state}}"
    path: "/etc/postgresql/14/main/postgresql.conf"
    line: |
      max_connections = 100
      shared_buffers = 2GB
      effective_cache_size = 6GB
      maintenance_work_mem = 512MB
      checkpoint_completion_target = 0.9
      wal_buffers = 16MB
      default_statistics_target = 100
      random_page_cost = 1.1
      effective_io_concurrency = 300
      work_mem = 5242kB
      min_wal_size = 1GB
      max_wal_size = 4GB
      max_worker_processes = 4
      max_parallel_workers_per_gather = 2
      max_parallel_workers = 4
      max_parallel_maintenance_workers = 2

- name: Does pg_hba.conf exist?
  stat: 
    path: /etc/postgresql/14/main/pg_hba.conf
  register: pg_hba_conf

- name: Update pg_hba.conf where folks can log in from
  when: pg_hba_conf.stat.exists
  notify: restart_postgres
  lineinfile:
    path: "/etc/postgresql/14/main/pg_hba.conf"
    line: "host all all 0.0.0.0/0 md5"
    state: "{{postgres_state}}"

- name: Update pg_hba.conf where folks can log in from
  when: pg_hba_conf.stat.exists
  notify: restart_postgres
  lineinfile:
    path: "/etc/postgresql/14/main/pg_hba.conf"
    line: "host all all ::/0 md5"
    state: "{{postgres_state}}"

- name: Update Role
  include_tasks: role.yml