---
- name: Update Debian based distros
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Configure Postgresql
  include_tasks: config.yml

- name: Update Consul
  include_tasks: consul.yml

- name: Update Role
  include_tasks: role.yml
