---
- name: Update Debian based distros
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Update Consul
  include_tasks: consul.yml

- name: Does postgresql.conf exist?
  stat: 
    path: /etc/postgresql/14/main/postgresql.conf
  register: postgresql_conf

- name: Update postgresql.conf for listening IPs
  when: postgresql_conf.stat.exists
  notify: restart_postgres
  lineinfile:
    path: "/etc/postgresql/14/main/postgresql.conf"
    line: "listen_addresses = '*'"
    state: "{{postgres_state}}"

- name: Does pg_hba.conf exist?
  stat: 
    path: /etc/postgresql/14/main/pg_hba.conf
  register: pg_hba_conf

- name: Update pg_hba.conf where folks can log in from
  when: pg_hba_conf.stat.exists
  notify: restart_postgres
  lineinfile:
    path: "/etc/postgresql/14/main/pg_hba.conf"
    line: "host all all 0.0.0.0/0 md5"
    state: "{{postgres_state}}"

- name: Update pg_hba.conf where folks can log in from
  when: pg_hba_conf.stat.exists
  notify: restart_postgres
  lineinfile:
    path: "/etc/postgresql/14/main/pg_hba.conf"
    line: "host all all ::/0 md5"
    state: "{{postgres_state}}"