---
- name: check directory status
  stat: 
    path: "{{ share_path }}/{{ item.share_name }}"
  register: directory_status

- name: create directory
  when: not directory_status.stat.exists
  file:
    path: "{{ share_path }}/{{ item.share_name }}"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: reset file permissions
  when: directory_status.stat.exists
  file:
    path: "{{ share_path }}/{{ item.share_name }}"
    state: directory
    mode: 0755
    group: root
    owner: root
    recurse: yes
