---
- name: Does /opt/kubeadm-config.yml exist?
  stat: 
    path: /opt/kubeadm-config.yml
  register: file

- name: Does/opt/calico-custom-resources.yml exist?
  stat: 
    path: /opt/calico-custom-resources.yml
  register: file2

- name: Create kubeadm-config file.
  when: not file.stat.exists
  template:
    src: kube-config.j2
    dest: "/opt/kubeadm-config.yml"
    owner: root
    group: root
    mode: 0644

- name: Create calico-system file.
  when: not file2.stat.exists
  template:
    src: calico-system.j2
    dest: "/opt/calico-custom-resources.yml"
    owner: root
    group: root
    mode: 0644