---
- name: install nginx
  apt:
    state: latest
    name: nginx
  notify: restart_nginx

- name: update default site to {{ ansible_host }}
  template:
    src: files/default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart_nginx
