---
- name: Update Centos based distros
  include_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Update Debian based distros
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: enable QEMU agent
  when: qemu_client is defined
  service:
    name: qemu-guest-agent
    enabled: yes
  notify: restart_qemu
