---
- name: Update Debian based distros
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Does /etc/consul.d exist?
  stat: 
    path: /etc/consul.d
  register: consul_d

- name: Create consul config file.
  when: not consul_d.stat.exists
  template:
    src: config.hcl
    dest: "/etc/consul.d/config.hcl"
    owner: consul
    group: consul
    mode: 0644