---
- name: Update Debian based distros
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Does /etc/consul.d exist?
  stat: 
    path: /etc/consul.d/config.hcl
  register: consul_d

- name: Create consul config file.
  notify: restart_consul
  template:
    src: config.hcl
    dest: "/etc/consul.d/config.hcl"
    owner: consul
    group: consul
    mode: 0644

- name: Does sites-available exist?
  stat: 
    path: /etc/nginx/sites-available
  register: sites_avail

- name: Create consul ui reverse-proxy config file.
  when: consul_ui and sites_avail.stat.exists
  template:
    src: nginx_ui.j2
    dest: "/etc/nginx/sites-available/default"
    owner: root
    group: root
    mode: 0644