---
- name: Update Debian based distros
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Does /etc/consul.d exist?
  stat: 
    path: /etc/consul.d
  register: consul_d