---
- name: Update Debian based distros
  include_tasks: install_debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Update update apt-cache resolvers
  include_tasks: install_resolvers.yml
  when: ansible_facts['os_family'] == "Debian"
