---
- name: Volatile Volumes on CALLISTO
  hosts: volatile_targets
  become: yes
  roles:
    - nfs_server
  vars:
    share_path: "/srv/nfs_shares"
    nfs_shares:
      - { share_name: volatile_zero }
      - { share_name: volatile_one }
      - { share_name: volatile_two }

- name: Mirrored Volumes on PONTOON
  hosts: mirrored_targets
  become: yes
  roles:
    - nfs_server
  vars:
    share_path: "/srv/nfs_shares"
    nfs_shares:
      - { share_name: mirrored_zero }
      - { share_name: mirrored_one }
      - { share_name: mirrored_two }

- name: Raid5 Volumes on GANYMEDE
  hosts: raid_five_targets
  become: yes
  roles:
    - nfs_server
  vars:
    share_path: "/srv/nfs_shares"
    nfs_shares:
      - { share_name: raid_five_zero }
      - { share_name: raid_five_one }
      - { share_name: raid_five_two }