---
- name: Volume Hosts
  hosts: volume_targets
  become: yes
  roles:
    - nfs_server
  vars:
    share_path: "/srv/m"
    nfs_shares:
      - { share_name: jenkinsData }
      - { share_name: octoprintData }

- name: FixingIps
  hosts: support_workers:kubernetes_workers:kubernetes_master
  become: yes
  roles:
    - fixed_ip
    
- name: Install Kubernetes
  hosts: kubernetes_workers:kubernetes_master
  become: yes
  roles:
    - docker
    - kubernetes



# https://opensource.com/article/20/6/kubernetes-raspberry-pi

# sudo sed -i '$ s/$/ cgroup_enable=memory cgroup_memory=1/' /boot/firmware/cmdline.txt && sudo reboot now

# sudo kubeadm init --kubernetes-version=v1.23.6 --pod-network-cidr=10.240.0.0/16 --service-cidr=10.241.0.0/16

# kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

# kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

# kubectl apply -f https://gist.githubusercontent.com/bbrietzke/c59b6132c37ea36f9b84f1fee701a642/raw/00e1683fbd7422fc297629128b08bded6ca3c90b/kubernetes-test.yaml




# kubeadm join 192.168.1.156:6443 --token q344rr.dm5sqivv6l1cw235 --discovery-token-ca-cert-hash sha256:11a65c8a9701f66b3699e3b8ca178c9a81779ec86d80dd942439a925213a0ab6 && sleep 30 && sudo systemctl daemon-reload && sudo systemctl restart kubelet
# kubeadm join 192.168.1.101:6443 --token fkam0j.0dvizychfdoe877j --discovery-token-ca-cert-hash sha256:620247c3e581631e1bd08c3129425bdea74da12805a3251916ff814b6ea08813 && sleep 30 && sudo systemctl daemon-reload && sudo systemctl restart kubelet
