---
  
# - name: Install NFS Servers
#   hosts: nfs_servers
#   become: yes
#   roles:
#     - nfs_server
#   vars:
#     subnet: "192.168.1.0/24"
#     share_path: "/srv/nfs_shares"
#     nfs_shares:
#       - { share_name: flamenco }

# - name: Install Samba for File Sharing
#   hosts: samba_servers
#   become: yes
#   roles:
#     - samba_server
#   vars:
#     workgroup: WORKGROUP
#     smb_shares:
#       - { share_name: 3dModels, comment: "STL Backup Directory" }
#       - { share_name: wargames, comment: "A place to save Wargame PDFs" }

- name: Consul Servers
  hosts: consul_servers
  become: yes
  roles:
    - consul
  vars:
    consul_server: true
    consul_ui: true
    consul_datacenter: basement

- name: Consul Agents
  hosts: consul_agents
  become: yes
  roles:
    - consul
  vars:
    consul_datacenter: basement
  
- name: PostgreSQL Servers
  hosts: postgresql_servers
  become: yes
  roles:
    - postgresql

- name: NoSQL and Cache Servers
  hosts: nosql
  become: yes
  roles:
    - redis
    - memcached

# - name: Install Vault Servers
#   hosts: vault_servers
#   become: yes
#   roles:
#     - vault
#   vars:
#     vault_use_consul: true
#     vault_use_http: true

# - name: Node Exporters
#   hosts: all
#   become: yes
#   roles:
#     - node_exporter