---
- name: ISCSI Setup
  hosts: iscsi_targets
  become: yes
  roles:
    - iscsi_target
    
- name: Install Kubernetes
  hosts: kubernetes
  become: yes
  roles:
    - docker
    - kubernetes



# https://opensource.com/article/20/6/kubernetes-raspberry-pi

# sudo sed -i '$ s/$/ cgroup_enable=memory cgroup_memory=1/' /boot/firmware/cmdline.txt && sudo reboot now

# sudo kubeadm init --kubernetes-version=v1.22.1 --pod-network-cidr=10.244.0.0/16

# kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

# kubectl taint node phobos node-role.kubernetes.io/master:NoSchedule-
# kubectl taint node phobos node-role.kubernetes.io/master:NoSchedule
# kubectl apply -f https://gist.githubusercontent.com/bbrietzke/c59b6132c37ea36f9b84f1fee701a642/raw/00e1683fbd7422fc297629128b08bded6ca3c90b/kubernetes-test.yaml





# sudo kubeadm join 192.168.1.179:6443 --token 2loxrr.wnbs4wcpg13dpked --discovery-token-ca-cert-hash sha256:c81af8e46c5cf2106e7484fec3751080e95e3b04393fa02ab618b87fab4eb30e && sleep 180 && sudo systemctl daemon-reload && sudo systemctl restart kubelet


# wjWECvf2aeNSQoqoQa0LdZJqSXru7hOB7wznJ2FFcMmi1vkeFwtlXTTD8CLUe9RM