---
all:
  hosts:
    titan:
      ansible_host: titan.local
      ansible_user: pi
  children:
    microservice_hosts:
      hosts:
        titan:
    microservice_message_broker:
      hosts:
        titan: