---
all:
  hosts:
    europa:
      ansible_host: europa.local
      ansible_user: pi
    callisto:
      ansible_host: callisto.local
      ansible_user: pi
  children:
    developer_workstations:
      hosts:
        callisto:
