---
all:
  hosts:
    dione:
      ansible_host: dione.local
      ansible_user: pi
    mimas:
      ansible_host: mimas.local
      ansible_user: pi
    tethys:
      ansible_host: tethys.local
      ansible_user: pi
  children:
    julia_hosts:
      hosts:
        mimas:
        tethys:
        dione:
  # children:
  #   microservice_hosts:
  #     hosts:
  #       tethys:
  #   microservice_message_broker:
  #     hosts:
  #       titan:
