---
all:
  hosts:
    orcus:
      ansible_host: orcus
      ansible_user: pi
    mimas:
      ansible_host: mimas
      ansible_user: pi
    enceladus:
      ansible_host: enceladus
      ansible_user: pi
    dione:
      ansible_host: dione
      ansible_user: pi
    tethys:
      ansible_host: tethys
      ansible_user: pi
  children:
    jupyter_servers:
      hosts:
        tethys:
    julia_hosts:
      hosts:
        tethys:
        dione:
  # children:
  #   microservice_hosts:
  #     hosts:
  #       tethys:
  #   microservice_message_broker:
  #     hosts:
  #       titan:
