---
all:
  hosts:
    io:
      ansible_host: io.local
      ansible_user: pi
    europa:
      ansible_host: europa.local
      ansible_user: pi
    ganymede:
      ansible_host: ganymede.local
      ansible_user: pi
    callisto:
      ansible_host: callisto.local
      ansible_user: pi
  children:
    buildbot_servers:
      hosts:
        io: