---
all:
  hosts:
    calypso:
      ansible_host: calypso.local
      ansible_user: pi
    callisto:
      ansible_host: callisto.local
      ansible_user: pi
  children:
    buildbot_servers:
      hosts:
        calypso:
    developer_workstations:
      hosts:
        callisto:
