---
all:
  hosts:
    orcus:
      ansible_host: orcus
      ansible_user: pi
    enceladus:
      ansible_host: iapetus
      ansible_user: ubuntu
    iapetus:
      ansible_host: iapetus
      ansible_user: ubuntu
    rhea:
      ansible_host: rhea
      ansible_user: ubuntu
    dione:
      ansible_host: dione
      ansible_user: ubuntu
    tethys:
      ansible_host: tethys
      ansible_user: ubuntu
  children:
    jupyter_servers:
      hosts:
        tethys:
    julia_hosts:
      hosts:
        tethys:
        dione:
        iapetus:
        rhea:
  # children:
  #   microservice_hosts:
  #     hosts:
  #       tethys:
  #   microservice_message_broker:
  #     hosts:
  #       titan:
