---
- name: install mosquitto/stable
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages: "{{ apt_packages }}"
  notify: restart_mqtt

- name: Update Consul
  include_tasks: consul.yml