---
ubuntu_version: hirsute

docker_state: present
  
remove_packages:
  - docker 
  - docker-engine 
  - docker.io 
  - containerd 
  - runc

add_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release