---
- name: Install required Cacher-NG packages
  apt:
    name: "{{ packages }}"
    state: "{{ cacher_state }}"
  vars:
    packages: "{{ cacher_packages }}"
  tags:
    - sw
    - apt

- name: Enable cacher-ng service
  systemd:
    name: apt-cacher-ng
    state: started
    enabled: true
    masked: false