---
- name: dist-upgrade
  apt:
    upgrade: dist
    update_cache: yes
  notify:
    - restart_machine
  tags:
    - sw
    - apt

- name: cleaning
  apt:
    autoclean: yes
    autoremove: yes
  notify:
    - restart_machine
  tags:
    - sw
    - apt

- name: standard_packages
  apt:
    name: "{{ package }}"
    state: present
  vars:
    package: "{{ packages }}"
