---
- name: install pip for python3
  apt:
    update_cache: yes
    state: present
    name: "{{ p }}"
  vars:
    p:
      - python3-pip

- name: install new pip
  pip:
    executable: /usr/bin/pip3
    extra_args: --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org
    state: latest
    name:
      - pip

- name: install RPi.GPIO
  pip:
    executable: /usr/bin/pip3
    extra_args: --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org
    state: latest
    name:
      - RPi.GPIO
