---
- name: install pip for python3
  apt:
    update_cache: yes
    state: present
    name: "{{ p }}"
  vars:
    p:
      - python3-pip

- name: install new pip
  pip:
    executable: {{ pip_executable }}
    extra_args: {{ pip_extras }}
    state: latest
    name:
      - pip

- name: install RPi.GPIO
  pip:
    executable: {{ pip_executable }}
    extra_args:  {{ pip_extras }}
    state: latest
    name:
      - RPi.GPIO
