---
- name: install pip for python3
  apt:
    update_cache: yes
    state: present
    name: "{{ p }}"
  vars:
    p:
      - python3-pip

- name: install new pip
  pip:
    extra_args: "-U"
    state: latest
    name:
      - pip

- name: install RPi.GPIO
  pip:
    executable: "{{ pip_executable }}"
    extra_args:  "{{ pip_extras }}"
    state: latest
    name: "{{ additional_pip_packages }}"

- name: update python3 to be default
  alternatives:
    name: python
    path: /usr/bin/python3
    priority: 1
