---
- name: Does /etc/slurm exist?
  stat: 
    path: /etc/slurm
  register: slurm_dir

- name: Create SLURM configuration file.
  when: slurm_dir.stat.exists
  template:
    src: slurm.conf.j2
    dest: "/etc/slurm/slurm.conf"
    owner: slurm
    group: slurm
    mode: 0644