---
common_tools:
  - tmux
  - git
  - vim

extra_packages:
  - wolfram-engine
  - libreoffice*
  - scratch
  - minecraft-pi
  - python-minecraftpi
  - python3-minecraftpi
  - sonic-pi
  - dillo
  - gpicview
  - penguinspuzzle

pi_password: $6$87T/wLITDDlZJhZW$9WgIv2scat1lnio4L73HPQikP7rbWLP0osHhncT.94PTqS/TFID0L5.xVykw6LzXeTIHyDZov.MOI15qz7buJ0
github_keys_url: ""
