---
- name: install tools
  apt:
    state: present
    name: "{{ packages }}"
  vars:
    packages: "{{ common_tools }}"
  tags:
    - sw
    - raspi
    - apt

- name: remove extra packages
  apt:
    name="{{ packages }}"
    state=absent
  vars:
    packages: "{{ extra_packages }}"
  tags:
    - sw
    - raspi
    - apt
