---
- name: Update Debian based distros
  include_tasks: install_debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Update /etc/hosts
  include_tasks: install_resolvers.yml

- name: Update update laptop clam shell suspend mode
  include_tasks: laptop_clamshell_updates.yml
  when: is_laptop

- name: Add user accounts
  include_tasks: add_users.yml