---
all:
  hosts:
    enceladus:
      ansible_host: enceladus.local
      ansible_user: pi
  children:
    web_servers:
      hosts:
        enceladus:
    developer_workstations:
      hosts:
        enceladus:
    jupyter_servers:
      hosts:
        enceladus:
