---
all:
  hosts:
    enceladus:
      ansible_host: enceladus.local
      ansible_user: pi
  children:
    developer_workstations:
      hosts:
        enceladus:
    buildbot_servers:
      hosts:
        enceladus:
          buildbot_title: "{{ansible_hostname}} Build Server"
    jupyter_servers:
      hosts:
        enceladus:
