---
# - name: Variables based on Operating system
#   include_vars: "{{ lookup('first_found', possible_files) }}"
#   vars:
#     possible_files:
#       - "roles/common/vars/{{ ansible_distribution }}.{{ ansible_distribution_major_version }}.yml"
#       - "roles/common/vars/{{ ansible_os_family }}.{{ ansible_distribution_major_version }}.yml"
#       - "roles/common/vars/default.yml"
#
# - name: Debugging variables
#   debug:
#     msg: "{{ ansible_distribution }}.{{ ansible_distribution_major_version }}.{{ ansible_os_family }}.{{ inventory_hostname }}"
#   tags:
#     - debug
#
# - debug:
#     msg: "{{ ansible_play_hosts }}"
#
# - debug:
#     msg: "{{ included_variable_one }}"
#
# - debug:
#     msg: "roles/common/vars/{{ ansible_distribution }}.yml"
