---
all:
  hosts:
    orcus:
      ansible_host: orcus.local
      ansible_user: pi
  children:
  # children:
  #   microservice_hosts:
  #     hosts:
  #       tethys:
  #   microservice_message_broker:
  #     hosts:
  #       titan:
