---
- name: install node exporter
  apt:
    name: "{{ package }}"
    state: "{{ package_state }}"
  vars:
    package: "{{ monitoring_packages }}"

- name: Update Consul
  include_tasks: consul.yml


