---

- name: Update for IPTables to enable bridging
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  notify:
    - restart_machine

- name: Copy containerd-config file.
  template:
    src: containerd-config.j2
    dest: "/etc/containerd/config.toml"
    owner: root
    group: root
    mode: 0644

- name: Daemon Mode
  include_tasks: adjust_daemon_mode.yml

- name: Update Debian based distros
  include_tasks: install_kubernetes_debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Make changes for Raspberry Pi's
  include_tasks: update_cgroups.yml
  when: ansible_facts['os_family'] == "Debian"


