---
- name: Daemon Mode
  include_tasks: adjust_daemon_mode.yml

- name: Update Debian based distros
  include_tasks: install_kubernetes_debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Make changes for Raspberry Pi's
  include_tasks: update_cgroups.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Does /etc/containerd/config.toml exist
  stat: 
    path: /etc/containerd/config.toml
  register: file

- name: Copy containerd-config file.
  template:
    src: containerd-config.j2
    dest: "/etc/containerd/config.toml"
    owner: root
    group: root
    mode: 0644
  when: file.stat.exists
