---

- name: Update for IPTables to enable bridging
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  notify:
    - restart_machine

- name: Update Debian based distros
  include_tasks: install_kubernetes_debian.yml
  when: ansible_facts['os_family'] == "Debian"


