---
- name: does Julia already live here?
  stat:
    path: "{{ julia_local }}/{{ julia_tar_path }}"
  register: julia_stat

- name: download and extract julia
  when: julia_stat.stat.exists == false
  unarchive:
    src: "{{ julia_url }}{{ julia_tar }}"
    dest: "{{ julia_local }}"
    remote_src: yes
    validate_certs: False

- name: add Julia user for distributed workloads
  user:
    name: julia
    shell: /usr/sbin/nologin
