---
primary_controller: pandora

suspend_timeout: 600
suspend_time: 60
suspend_rate: 10
resume_timeout: 600
resume_rate: 10

partition_config:
  - { name: "slicers", nodes: "worker0[0-1]", default: false, max_time: 600, disabled: true }

node_config:
  - { name: "worker0[0-1]", cpus: 2, real_memory: 1024 }