---

consul_state: present

consul_encryption_key: r8joTsIluCHCxxoMwbDoetgJM19nKrR0vbtYBTB7MU0=
consul_data_dir: /opt/data
consul_ui: false
consul_server: false
consul_datacenter: datacenter_one

consul_packages:
  - consul