---

- name: Install Vault GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: "{{ vault_state }}"

- name: Install Vault APT Repository
  apt_repository: 
    repo: "deb https://apt.releases.hashicorp.com {{ ubuntu_version }} main"
    state: "{{ vault_state }}"

- name: Install Vault packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: "{{ vault_state }}"
  vars:
    packages: "{{ vault_packages }}"


- name: Enable Vault
  service:
    name: vault
    enabled: yes