---
- name: Update Debian based distros
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Create Vault config file.
  notify: restart_vault
  template:
    src: vault.j2
    dest: "/etc/vault.d/vault.hcl"
    owner: vault
    group: vault
    mode: 0644