---
- name: lets do some debugging
  debug:
    msg: my ipv4 is {{ ansible_facts.wlan0.ipv4.address }}
  when: ansible_facts.wlan0.ipv4.address is defined

- name: install additional PIP packags
  pip:
    executable: "{{ pip_executable }}"
    extra_args:  "{{ pip_extras }}"
    state: latest
    name: "{{ pip_packages }}"

- name: Init Docker Swarm on Host
  docker_swarm:
    state: present
    advertise_addr: "{{ ansible_facts.wlan0.ipv4.address }}:2377"
  when: ansible_facts.wlan0.ipv4.address is defined
