---
- name: install prerequistes
  apt:
    name: "{{ p }}"
  vars:
    p:
      - npm
      - nodejs

- name: web proxy
  npm:
    name: configurable-http-proxy
    global: yes
    state: present

- name: install JupyterHub
  pip:
    name:
      - notebook
      - jupyterhub
      - jupyterlab
      - oauthenticator
    executable: "{{ pip_executable }}"
    extra_args:  "{{ pip_extras }}"
    umask: "0022"
    state: latest

- name: /etc/JupyterHub
  file:
    path: "/etc/jupyterhub"
    state: directory

- name: jupyterhub_config.py
  copy:
    src: "files/jupyterhub_config.py"
    dest: "/etc/jupyterhub/jupyterhub_config.py"
    force: no

- name: jupyterhub.service
  copy:
    src: "files/jupyterhub.service"
    dest: "/etc/systemd/system/jupyterhub.service"
    force: no

- name: add jupyterhub.local as an available site
  template:
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart_nginx
