---
- name: install prerequistes
  apt:
    name: "{{ p }}"
  vars:
    p:
      - npm
      - nodejs

- name: web proxy
  npm:
    name: configurable-http-proxy
    global: yes
    state: present

- name: install JupyterHub
  become: yes
  pip:
    name:
      - notebook
      - jupyterhub
      - jupyterlab
      - oauthenticator
    executable: "/usr/local/bin/pip3"
    umask: "0022"
    extra_args: --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host piwheels.org
    state: latest

- name: /etc/JupyterHub
  file:
    path: "/etc/jupyterhub"
    state: directory

- name: jupyterhub_config.py
  copy:
    src: "files/jupyterhub_config.py"
    dest: "/etc/jupyterhub/jupyterhub_config.py"
    force: no

- name: jupyterhub.service
  copy:
    src: "files/jupyterhub.service"
    dest: "/etc/systemd/system/jupyterhub.service"
    force: no

- name: add {{ ansible_default_ipv4.address }} as jupyterhub.local to mDNS
  lineinfile:
    path: /etc/avahi/hosts
    state: present
    line: "{{ ansible_default_ipv4.address }} hub.local"
  notify: restart_avahi

- name: add jupyterhub.local as an available site
  template:
    src: files/jupyter.conf.j2
    dest: /etc/nginx/sites-available/jupyter
    owner: root
    group: root
    mode: 0644

- name: symlink to enable jupyterhub.local
  file:
    src: /etc/nginx/sites-available/jupyter
    dest: /etc/nginx/sites-enabled/jupyter
    state: link
  notify: restart_nginx
