---
- name: Install prerequistes
  apt:
    name: "{{ p }}"
  vars:
    p:
      - npm
      - nodejs

- name: Web Proxy
  npm:
    name:
      - configurable-http-proxy
    global: yes
    state: present

- name: Install JupyterHub
  pip:
    name:
      - notebook
      - jupyterhub
    cmd: "/usr/bin/pip3"
    state: present
