---
- name: install prerequistes
  apt:
    name: "{{ p }}"
  vars:
    p:
      - npm
      - nodejs

- name: web proxy
  npm:
    name: configurable-http-proxy
    global: yes
    state: present

- name: install JupyterHub
  pip:
    name:
      - notebook
      - jupyterhub
      - oauthenticator
    executable: "/usr/bin/pip3"
    state: present

- name: /etc/JupyterHub
  file:
    path: "/etc/jupyterhub"
    state: directory

- name: jupyterhub_config.py
  copy:
    src: "files/jupyterhub_config.py"
    dest: "/etc/jupyterhub/jupyterhub_config.py"
    force: no

- name: jupyterhub.service
  copy:
    src: "files/jupyterhub.service"
    dest: "/etc/systemd/system/jupyterhub.service"
    force: no


