---
- name: set TZ to US/Central
  timezone:
    name: "US/Central"

- name: set locale to US/UTF8
  locale_gen:
    name: en_US.UTF-8
    state: present
  notify: update locales



- name: /etc/dphys-swapfile
  notify: restart_machine
  copy:
    src: "files/dphys-swapfile"
    dest: "/etc/dphys-swapfile"
    force: yes

- name: Change pi password
  user:
    name: pi
    password: "{{ pi_password }}"

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart_ssh

- name: ssh without passwords
  authorized_key:
    user: pi
    state: present
    key: "{{ github_keys_url }}"

- name: update all packages
  apt:
    name: "*"
    state: latest

- name: install tools
  apt:
    name: "{{ p }}"
    state: present
  vars:
    p:
      - screen
      - python3
      - python3-pip
