---
- name: ssh without passwords
  authorized_key:
    user: pi
    state: present
    key: https://github.com/bbrietzke.keys

- name: update all packages
  apt:
    name: "*"
    state: latest

- name: install tools
  apt:
    name: "{{ p }}"
  vars:
    p:
      - screen
      - python3
      - python3-pip3
