---
- name: Install ElasticSearch GPG key
  apt_key:
    url: https://packages.redis.io/gpg
    state: "{{ elastic_state }}"
  tags:
    - sw
    - gpg

- name: Install ElasticSearch APT Repository
  apt_repository: 
    repo: deb https://packages.redis.io/deb jammy main
    state: "{{ elastic_state }}"
  tags:
    - sw
    - apt

- name: Install ElasticSearch packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: "{{ elastic_state }}"
  vars:
    packages: "{{ elastic_packages }}"
