---
# vars file for mariadb
mariadb_config_file:
  mysqld:
    - "user = mysql"
    - "port = 3306"
    - "datadir = /var/lib/mysql"
    - "skip-external-locking"
    - "key_buffer_size	= 16M"
    - "max_allowed_packet	= 16M"
    - "thread_stack	= 192K"
    - "thread_cache_size = 8"
    - "query_cache_size  = 32M"
    - "log_error = /var/log/mariadb/error.log"
    - "unix_socket=OFF"
mariadb_service: mariadb