---
- name: check image status
  stat: 
    path: "{{ disk_image_path }}/{{ item.lun_name }}.img"
  register: image_status

- name: check LUN status
  stat: 
    path: "{{ tgt_path }}/{{ item.lun_name }}.img"
  register: lun_status

- name: LUN configuration
  when:  not lun_status.stat.exists
  template: 
    src: lun_workbook.j2
    dest: "{{ tgt_path }}/{{ item.lun_name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    -  restart_targets

- name: create disk image if not present
  when:  not image_status.stat.exists
  command:
    cmd: dd if=/dev/zero of={{ disk_image_path }}/{{ item.lun_name }}.img count=0 bs=1 seek={{ item.disk_image_size }}