---

- name: check directory status
  stat: 
    path: "{{ disk_image_path }}"
  register: directory_status

- name: check image status
  stat: 
    path: "{{ disk_image_path }}/{{ lun_name }}.img"
  register: image_status

- name: create directory
  when:  directory_status.stat.exists == false
  file:
    path: "{{ disk_image_path }}"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: create disk image if not present
  when: image_status.stat.exists == false
  shell:
    cmd: dd if=/dev/zero of={{ disk_image_path }}/{{ lun_name }}.img count=0 bs=1 seek={{ disk_image_size }}
