---

- name: check directory status
  stat: 
    path: "{{ disk_image_path }}"
  register: directory_status

- name: create directory
  when:  directory_status.stat.exists == false
  file:
    path: "{{ disk_image_path }}"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: create disk image if not present
  include_tasks: create_disk_image.yml
  loop: "{{ disk_images }}"
