---
- name: Is this a Raspberry Pi?
  stat: 
    path: "/boot/octopi.txt"
  register: camera_status   

- name: Update /boot/octopi.txt to turn on the camera
  when: camera_status.stat.exists
  notify: restart_machine
  lineinfile:
    path: "/boot/octopi.txt"
    regexp: "#camera="auto""
    line: "camera=\"raspi\""
    state: present

- name: Update /boot/octopi.txt for cgroups
  when: camera_status.stat.exists
  notify: restart_machine
  lineinfile:
    path: "/boot/octopi.txt"
    regexp: "#camera_usb_options=\"-r 640x480 -f 10\""
    line: "camera_usb_options=\"-r 1920x1080 -f 15\""
    state: present