---
- name: install memcached/stable
  apt:
    name: "{{ p }}"
    state: present
  vars:
    p:
      - memcached
  notify: restart_mqtt

- name: copy over memcached.conf
  template:
    src: "templates/memcached.conf.j2"
    dest: "/etc/memcached.conf"
    owner: memcached
    group: memcached
    mode: 0644
  notify: restart_mqtt