---
- name: install memcached/stable
  apt:
    name: "{{ p }}"
    state: present
  vars:
    p:
      - memcached

- name: copy over memcached.conf
  template:
    src: "templates/memcached.conf.j2"
    dest: "/etc/memcached.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart_mqtt

- name: Update Consul
  include_tasks: consul.yml

- name: Update Role
  include_tasks: role.yml