---
julia_tar: julia-1.0.3-linux-armv7l.tar.gz
julia_url: https://julialang-s3.julialang.org/bin/linux/armv7l/1.0/
julia_tar_path: /julia-1.0.3
julia_local: /opt
github_keys_url: https://github.com/bbrietzke.keys

pi_password: $6$mgqgJWrIRgrXodXK$YLXgsW3XkZADQPGMiF8bjxP43mw5Q4GxaTXl5pmrX7ANcAphKAiV47F0TWorIl5X8t4a3eFpKa8AgAz5cE6O5/

normal_user: bbrietzke
normal_user_password: $6$mgqgJWrIRgrXodXK$YLXgsW3XkZADQPGMiF8bjxP43mw5Q4GxaTXl5pmrX7ANcAphKAiV47F0TWorIl5X8t4a3eFpKa8AgAz5cE6O5/

common_tools:
  - screen
